### ISSUE TITLE
Disable login

### ISSUE THREAD

**Issue by tip2663** [mCaptcha/mCaptcha#164]
Hello! cool project, but i have a security concern:

after I have set up the instance over docker and created an account:
how would i proceed to disable the login page, disallowing others from login attempts?

Seeing that clients must include the widget directly by querying the server for its widget, I figured it won't work to just not expose mcaptcha to the public.

My idea is to set up a reverse proxy to mcaptcha that only allows routes that are required for PoW - but do you think that is viable?

Thanks

(PS: i think it would be nice if the login page is protected by mcaptcha itself ;) )

Edit:
I think i have it set up. With this config, only the client-facing widget and the API that is required for it to work is needed.
Rest is hidden away and can be accessed only within the docker network, so that  backend code can fire http-requests on the unguarded verification api

here's the nginx conf (in my setup located in the file `./mcaptcha_nginx/mcaptcha.conf`):
```
upstream mcaptcha {
  server        mcaptcha:7000;
}
server {
  listen        80;
  server_name   localhost;

  location ~ (/widget|/assets|/api/v1/pow/verify|/api/v1/pow/config) {
    proxy_pass  http://mcaptcha;
  }
}
```

And here's how i added it to the docker compose.

```
version: '3'

services:
  mcaptcha_public_reverse:
    image: nginx
    ports:
      - 7000:80
    volumes:
      - ./mcaptcha_nginx/mcaptcha.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mcaptcha
```
