### ISSUE TITLE
Troubles with ports using docker 

### ISSUE THREAD

**Issue by CartierPierre** [mCaptcha/mCaptcha#31]
Hi,
I'm trying to run mCaptcha with docker compose, on a server that already have some redis and postgres containers mapped on 6379 and 5432.

I tried to map postgres and redis on other port, but the main app doesn't recognise.

Here is my conf file :
``` yaml
version: '3.9'

services:
  mcaptcha:
    image: mcaptcha/mcaptcha:latest
    ports:
      - 7000:7000
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5433/postgres # set password at placeholder
      MCAPTCHA_REDIS_URL: redis://mcaptcha-redis:6380/
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      PORT: 7000
    depends_on:
      - postgres
      - mcaptcha-redis

  postgres:
    image: postgres:13.2
    ports:
      - "5433:5432"
    volumes:
      - mcaptcha-data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: password # change password
      PGDATA: /var/lib/postgresql/data/mcaptcha/

  mcaptcha-redis:
    image: mcaptcha/cache:latest
    ports:
      - "6380:6379"

volumes:
  mcaptcha-data:
```
