### ISSUE TITLE
MCaptchaRediSModuleCommandNotFound error while deploying with Docker

### ISSUE THREAD

**Issue by pitininja** [mCaptcha/mCaptcha#56]
Hello,

I've tried to deploy mCaptcha with Docker and I have an error that I'm not able to fix:

```
Version: 0.1.0 commit: c1f6ce3ae29321f0fdecf801ba789f60e4f89511
 INFO  mcaptcha::settings > Loading config file from /etc/mcaptcha/config.toml
 INFO  mcaptcha::data     > Initializing credential manager
 INFO  sqlx::postgres::notice > relation "_sqlx_migrations" already exists, skipping
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MCaptchaRediSModuleCommandNotFound("MCAPTCHA_CACHE.ADD_VISITOR")', src/data.rs:140:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Below is my Docker compose:

```yaml
version: '3'

services:
  mcaptcha:
    container_name: mcaptcha
    image: mcaptcha/mcaptcha:latest
    restart: always
    volumes:
      - /opt/mcaptcha/config.toml:/etc/mcaptcha/config.toml
    networks:
      - mcaptcha-network
      - postgresql-network
    ports: 
      - 127.0.0.1:7000:7000
  mcaptcha-redis:
    image: redis:latest
    container_name: mcaptcha-redis
    restart: always
    networks:
      - mcaptcha-network

networks:
  mcaptcha-network:
    name: mcaptcha
  postgresql-network:
    name: postgresql
    external: true
```

And here is my config file:

```toml
debug = false
source_code = "https://github.com/mCaptcha/mCaptcha"
commercial = false
allow_demo = false
allow_registration = false

[server]
cookie_secret = "******"
port = 7000
ip = "0.0.0.0"
domain = "mcaptcha.domain.com"
proxy_has_tls = true

[captcha]
salt = "******"
gc = 30
runners = 4
queue_length = 2000
enable_stats = true

[captcha.default_difficulty_strategy]
avg_traffic_difficulty =  50000
peak_sustainable_traffic_difficulty = 3000000
broke_my_site_traffic_difficulty = 5000000
duration = 30

[database]
hostname = "postgresql"
port = "5432"
username = "******"
password = "******"
name = "mcaptcha"
pool = 4
database_type="postgres"

[redis]
url = "redis://mcaptcha-redis/"
pool = 4

[smtp]
from = "admin@localhost"
reply = "admin@localhost"
url = "127.0.0.1"
port = 10025
username = "admin"
password = "password"
```

Thanks for any help
