### ISSUE TITLE
Disabling registration and demo on docker not working.

### ISSUE THREAD

**Issue by WardPearce** [mCaptcha/mCaptcha#79]
Greetings,
The following docker configuration still allows account registration and the demo account.

```yaml
version: "3.9"

services:
  mcaptcha:
    image: mcaptcha/mcaptcha:latest
    ports:
      - 7000:7000
    environment:
      DATABASE_URL: postgres://postgres:epic_password@mcaptcha_postgres:5432/postgres
      MCAPTCHA_REDIS_URL: redis://mcaptcha_redis/
      MCAPTCHA_SERVER_DOMAIN: mcaptcha.epic_domain.com
      MCAPTCHA_COMMERCIAL: false
      MCAPTCHA_ALLOW_REGISTRATION: false
      MCAPTCHA_ALLOW_DEMO: false
      RUST_LOG: debug
      PORT: 7000
    depends_on:
      - mcaptcha_postgres
      - mcaptcha_redis

  mcaptcha_postgres:
    image: postgres:13.2
    volumes:
      - mcaptcha-data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: epic_password
      PGDATA: /var/lib/postgresql/data/mcaptcha/

  mcaptcha_redis:
    image: mcaptcha/cache:latest

volumes:
  mcaptcha-data:
    driver: local
```
